version: 0.0.{build}-ci
image: Ubuntu
init:
- pwsh: >-
    $tagRelease = $env:appveyor_repo_tag -eq 'true'

    if ($tagRelease) {
        $tag = $env:appveyor_repo_tag_name
        Update-AppveyorBuild -Version "$tag"
    }
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  DOCKER_USERNAME:
    secure: jj922IXnopwoX3M9WFaP8g==
  DOCKER_PASSWORD:
    secure: z0QkG5dMUovqmdiVrojAAA==
build_script:
- pwsh: ./build.ps1 -BuildVersion "$env:APPVEYOR_BUILD_VERSION" -Release "$env:APPVEYOR_REPO_TAG" -DockerUsername "$env:DOCKER_USERNAME" -DockerPassword "$env:DOCKER_PASSWORD"