version: 0.0.{build}-ci
image: Ubuntu
init:
- pwsh: >-
    $tagRelease = $env:appveyor_repo_tag -eq 'true'

    if ($tagRelease) {
        $tag = $env:appveyor_repo_tag_name
        Update-AppveyorBuild -Version "$tag"
    }
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- pwsh: docker build -t silvenga/emissary -f src/Emissary/Dockerfile .