name: "Build"
on:
  pull_request:
  push:
    branches:
      - master
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Detect Version
      run: |
        $ref = '${{ github.ref }}'
        if ($ref.StartsWith('refs/tags/'))
        {
            $version = ($ref -split '/' | Select-Object -Last 1)
        }
        else
        {
            $version = "0.0.1"
        }

        Write-Host "Detected version: '$version'."
        Write-Host "::set-env name=BUILD_VERSION::$version"
      shell: pwsh

    - name: Build
      run: docker build --build-arg BUILD_VERSION=${{ env.BUILD_VERSION }} .

    - name: Publish (On Release Tags)
      uses: jerray/publish-docker-action@v1.0.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        file: Dockerfile
        path: .
        repository: silvenga/emissary
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        auto_tag: true
        build_args: BUILD_VERSION=${{ env.BUILD_VERSION }}
