name: "Build"
on:
  pull_request:
  push:
    branches:
      - master
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: docker build --pull -f Dockerfile --cache-from silvenga/emissary:latest .

    - name: Create Tags (On Release Tags)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        $ref = '${{ github.ref }}'

        $version = ($ref -split '/' | Select-Object -Last 1)

        $versionParts = $version -split "\."
        if ($versionParts.Count -ne 3)
        {
            throw "Invalid tag format '$version'."
        }

        $major = $versionParts[0]
        $minor = $versionParts[1]
        $patch = $versionParts[2]

        Write-Host "Got version '$major.$minor.$patch'."

        $imageTags = @(
            "$major.$minor.$patch",
            "$major.$minor",
            "$major",
            "latest"
        ) 

        $imageTagsList = $imageTags -join ","

        Write-Host "Built tags list: '$imageTagsList'."
        Write-Host "::set-env name=GENERATED_TAGS::$imageTagsList"
      shell: pwsh

    - name: Publish Latest (On Release Tags)
      uses: jerray/publish-docker-action@v1.0.4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        file: Dockerfile
        path: .
        repository: silvenga/emissary
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ env.GENERATED_TAGS }}